### ISSUE TITLE
No 'library' folder in package

### ISSUE THREAD

**Issue by ckombo** [subject117/Camera3D#1]
Hi, When I try to install Camera3D using processing's built-in library install method I get a 'no library found in installer' error. When I download the package here on GitHub, I see there's no folder called library in the download.

**Comment by hx2A** [comment]
Thank you for raising the issue. The problem behind the "no library found in installer" error was that I modified my website ixora.io to redirect HTTP requests to HTTPS requests. The processing library installer won't follow redirects and would instead try to install the redirect response as a library. That didn't work. I updated my library information with the Processing folks so it should now work correctly.
