### ISSUE TITLE
exporting vectors instead of pixels

### ISSUE THREAD

**Issue by zkg** [subject117/Camera3D#3]
Hi there. Congrats on the job so far - this looks like a solid library. 
I'm working with a Monoscopic 360 camera. Exporting frames as images works as expected, but if I try to export vectors (with beginRaw or beginRecord to SVG) the output is all jumbled. What would it take to apply the same distortion I see on the camera to the vectors themselves? I wonder if this question even makes sense.

**Comment by hx2A** [comment]
Thank you very much, I appreciate it.

I'm not quite sure what you are trying to do. Can you provide a simple code example for me to work with? Can you also tell me your vision for what you'd like to accomplish with beginRaw/beginRecord and Camera3D?

**Comment by zkg** [comment]
I'm trying to export a 360 view as SVG instead of using the frame saver provided with the library. 
Using 
`camera3D.renderMonoscopic360().setOutputSizeAndLocation(1024, "frames/sketch_#####.png");`
I can produce a frame like this, which makes sense:
![sketch](https://user-images.githubusercontent.com/13556865/81443170-c3a0bf80-9129-11ea-946f-266c79a745d2.png)
If I try to save the shapes of my sketch using beginRaw ( https://processing.org/reference/beginRaw_.html ), like this
`beginRaw(SVG, "output_"+frameCount+".svg");
box(boxSize);
endRaw();
`
the output is jumbled up:
![image](https://user-images.githubusercontent.com/13556865/81445424-ad94fe00-912d-11ea-89a7-58024f58a811.png)

Actual svg: [sketch.zip](https://github.com/hx2A/Camera3D/files/4601330/sketch.zip)

**Comment by hx2A** [comment]
I see what you are talking about. Can you copy-paste the code you used to create this?

**Comment by zkg** [comment]
Sure, it's just a variation of one of your examples:

`import camera3D.*;
import processing.svg.*;

Camera3D camera3D;

float rot = 75f;
float rotX = rot * 0.5f;
float rotY = rot * 0.1f;
float rotZ = rot * 0.3f;

void setup() {
  size(1200, 600, P3D);
  colorMode(HSB, 360, 100, 100);

  camera3D = new Camera3D(this);
  camera3D.renderMonoscopic360().setOutputSizeAndLocation(1024, "frames/sketch_#####.png");
  camera3D.setBackgroundColor(color(360, 0, 100));
  camera3D.camera(0, 0, 0, 0, 0, -1, 0, 1, 0);
}

void preDraw() {
  rot += 1;
  rotX = rot * 0.5f;
  rotY = rot * 0.1f;
  rotZ = rot * 0.3f;
}

void mouseReleased() {
  save("frame.png"); //Processing default pixel exporter https://processing.org/reference/save_.html
  if (mouseButton == RIGHT){ 
        beginRaw(SVG, "output_"+frameCount+".svg"); //https://processing.org/reference/beginRaw_.html
    }
}

void draw() {
  strokeWeight(1);
  stroke(0);

  int boxSize = 50;
  for (int y = -750; y <= 750; y += 750) {
    for (int theta = 0; theta < 360; theta += 180) {
      pushMatrix();
      fill(theta, 100, 50);
      rotateY(radians(theta));
      translate(0, y, -250);
      rotateX(radians(rotX));
      rotateY(radians(rotY));
      rotateZ(radians(rotZ));
      box(boxSize);
      popMatrix();
    }
  }
  if (mouseButton == RIGHT)
    endRaw();
}`

**Comment by hx2A** [comment]
Camera3D cannot output 360 SVG image files. Consider how Camera3D works:

http://ixora.io/projects/camera-3D/monoscopic-360-video/

It can render 6 square camera views and then re-shuffle all of the pixels into a single equirectangular image. If one of the 6 camera views sees a straight line, that line most likely will not be straight after it is placed in the equirectangular image.

Now think about SVG images and what vector graphics are. How will the SVG image record the distorted line? It has no good way of doing that. It will try to do _something_ but as you see it is not what you want.

Also note from the [Processing documentation](https://processing.org/reference/libraries/svg/index.html) that the SVG library will flatten 3D geometry:

> The SVG library can flatten 3D data into a 2D vector file, but to export 3D data, use the DXF library.

Also, the PDF and DXF libraries won't work either.

**Comment by zkg** [comment]
Thanks for your explanation. Indeed flattened 3D is what I'm looking for. It's not obvious to me why it wouldn't be possible to record an originally straight line as a curve. The naive approach would be, for every line, sampling points at any level of resolution, plotting them after the transformation, and join them with curved lines. But I can appreciate how that is not within the scope of Camera3D. Thanks anyway for your help!

**Comment by hx2A** [comment]
> The naive approach would be, for every line, sampling points at any level of resolution, plotting them after the transformation, and join them with curved lines. But I can appreciate how that is not within the scope of Camera3D.

The first part of that is exactly how Camera3D works. It samples pixels and remaps them into the equirectangular projection. It only understands pixels, not the lines and shapes that compose vector graphics like SVG files. I see what you are talking about though, it should be at least theoretically possible for a straight line to be remapped into a set of small lines that curve in a way that matches what Camera3D does. If this is something you want to accomplish, I would recommend looking at Python to do the necessary math and SVG file creation.

**Comment by zkg** [comment]
Thanks, I'm looking into it!
